language: python
sudo: required
python:
  - 3.5
  - 2.7
branches:
  only:
    - malin
    - bartek
    - malin-development
    - ania
    - master
script:
    - python -m setup.py install
    - python -m pytest ../tests
env:
    - PYTHONPATH=..\core\