language: python
sudo: required
python:
  - 3.4
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source=py_proj_lights Tests/all_tests.py
after_success:
  - coveralls
branches:
  only:
    - malin-development
before_install:
 - chmod -R 777 Simulation
 - chmod -R +x Tests/all_tests.py
 - sudo apt-get build-dep python-pygame
 - sudo apt-get install python-dev
