language: python
sudo: required
python:
  - 3.4
branches:
  only:
    - malin-development
before_install:
    - pip install -r requirements-tests.txt
install:
    - python setup.py
script:
    - python Tests/all_tests.py
